name: CI/CD Pipeline for Amrinaas Web Portfolio
  
on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Get latest code  
      uses: actions/checkout@v3  
  
    - name: Set up Node.js  
      uses: actions/setup-node@v3  
      with:  
        node-version: '18'  
  
    - name: Install dependencies  
      run: npm install  
  
    - name: Run tests  
      run: npm test -- --watchAll=false --passWithNoTests 
  
    - name: Build the app  
      run: npm run build  
  
    - name: Upload build artifact  
      uses: actions/upload-artifact@v3  
      with:  
        name: build  
        path: build  
  
  deploy:  
    needs: build  
    runs-on: ubuntu-latest  
    if: github.ref == 'refs/heads/main'  
  
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v3  
  
    - name: Set up Node.js  
      uses: actions/setup-node@v3  
      with:  
        node-version: '18'  
  
    - name: Install dependencies  
      run: npm install  
  
    - name: Build the app  
      run: npm run build  
  
    - name: Deploy to FTP  
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:  
        server: ftp.samkirkland.com
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: build/
        remote-dir: /home/itsamrin/public_html/ 
        
